"""empty message

Revision ID: d4759c7c76d0
Revises: 
Create Date: 2019-03-05 17:56:22.885643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4759c7c76d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_lkp_pay_mode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pay_mode', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=2), nullable=True),
    sa.Column('show_level', sa.String(length=2), nullable=True),
    sa.Column('gmt_create', sa.Date(), nullable=False),
    sa.Column('gmt_modified', sa.Date(), nullable=False),
    sa.Column('remark', sa.String(length=512), nullable=False),
    sa.Column('extension', sa.String(length=2000), nullable=True),
    sa.Column('dw_create_time', sa.Date(), nullable=False),
    sa.Column('dw_modified_time', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_lkp_product_catagory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('catagory_v1', sa.String(length=64), nullable=False),
    sa.Column('catagory_v2', sa.String(length=64), nullable=False),
    sa.Column('catagory_v3', sa.String(length=64), nullable=True),
    sa.Column('catagory_v4', sa.String(length=64), nullable=True),
    sa.Column('catagory_v5', sa.String(length=64), nullable=True),
    sa.Column('catagory_v6', sa.String(length=64), nullable=True),
    sa.Column('pay_channel_code', sa.String(length=64), nullable=False),
    sa.Column('pay_channel_name', sa.String(length=64), nullable=False),
    sa.Column('biz_prod_code', sa.String(length=64), nullable=False),
    sa.Column('biz_prod_name', sa.String(length=64), nullable=False),
    sa.Column('dw_create_time', sa.Date(), nullable=False),
    sa.Column('dw_modify_time', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimension',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('key_person', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('dimension')
    op.drop_table('dim_lkp_product_catagory')
    op.drop_table('dim_lkp_pay_mode')
    # ### end Alembic commands ###
